FROM java:8

EXPOSE 8091

CMD java -classpath src/main/java EurekaServerApplication com.esprit.microservice

ADD /target/Eureka_Server-0.0.1-SNAPSHOT.jar eureka_server.jar

ENTRYPOINT ["java","-jar","eureka_server.jar"]