version: "2.2"
services:

  User_backend:
    container_name: User_backend
    build: .\AxelibBackend
    ports:
      - "8080:8080"
    hostname: user_back
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "user_back"
    depends_on:
      - Eureka
    
  Concours_backend:
    container_name: concours_backend
    build: .\spring-boot-server
    ports:
      - "4646:4646"
    hostname: concours_back
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "concours_back"
    depends_on:
      - Eureka

  Fournisseur_backend:
    container_name: Fournisseur_backend
    build: .\FournisseurBackend
    ports:
      - "9465:9465"
    hostname: fournisseur_back
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "fournisseur_back"
    depends_on:
      - Eureka

  Book:
    container_name: book
    build: .\BookMS
    ports:
      - "8083:8083"
    hostname: book
    environment:      
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "book"
    depends_on:
      - Eureka      

  Eureka:
    container_name: serviceregistry
    build: .\Eureka_Server
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/

  Event:
    container_name: Event
    build: .\springboot-backend
    ports:
      - "9090:9090"
    hostname: event_back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/evt?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "event_back"
    depends_on:
      - Eureka
      - docker-mysql

  docker-mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=evt
    ports:
      - "3306:3306"
      
  Eureka:
    container_name: serviceregistry
    build: .\Eureka_Server
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  
  # Zuul:
  #   container_name: Zuul
  #   image: "zuul"
  #   build: .\Zuul-Gateway
  #   ports:
  #     - "8763:8763"
  #   hostname: Zuul
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  #   depends_on:
  #     - "Eureka"

  
  
  # Mongo:
  #   container_name: Mongo
  #   image: "mongo:5-focal"
  #   ports:
  #     - "27017:27017"
  #   hostname: Mongo
  #   depends_on:
  #     - "Eureka"
  
  # agence:
  #   container_name: agence
  #   image: "agence"
  #   build: .\MS-agence
  #   ports:
  #     - "5000:5000"
  #   hostname: agence
  #   depends_on:
  #     - "Eureka"
  #     - "Mongo"
  #   command: "node ./src/app.js"


  # auth:
  #   container_name: auth
  #   image: "auth"
  #   build: .\MS-auth
  #   ports:
  #     - "7000:7000"
  #   hostname: auth
  #   depends_on:
  #     - "Eureka"
  #     - "Mongo"
  #   command: "node ./src/app.js"


  
  
  # operation:
  #   container_name: operation
  #   image: "operation"
  #   build: .\MS.Operation
  #   ports:
  #     - "6000:6000"
  #   hostname: operation
  #   depends_on:
  #     - "Eureka"
  #     - "docker-mysql_3"
  #   command: "node index.js"